version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        entrypoint: php artisan octane:frankenphp --max-requests=1 --admin-port=2019 --port=8000
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        networks:
            - laravel
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "8080:80"
            - "443:443"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/cert:/etc/ssl/certs
        depends_on:
            - web
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql-data:
        driver: local
