version: "3.8"

services:
    web:
        image: dunglas/frankenphp
        restart: always
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        entrypoint: php artisan octane:frankenphp --max-requests=1 --https --http-redirect
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        ports:
            - '${APP_PORT:-80}:80'
            - "443:443" # HTTPS
            - "443:443/udp" # HTTP/3
        volumes:
            - .:/app
            - caddy_data:/data
            - caddy_config:/config
        networks:
            - laravel
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    caddy_data:
    caddy_config:
    mysql-data:
        driver: local
