version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        container_name: laravel_app
        working_dir: /var/www/html
        environment:
            - APP_ENV=production
            - APP_DEBUG=false
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
        networks:
            - laravel
        depends_on:
            - db
        volumes:
            - .:/var/www/html
            - ./storage:/var/www/html/storage
        expose:
            - "9000"

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        volumes:
            - .:/var/www/html:ro
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        networks:
            - laravel
        depends_on:
            - app
        ports:
            - "80:80"
            - "443:443"

    db:
        image: mysql:8.0
        container_name: laravel_db
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel

    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot

networks:
    laravel:
        driver: bridge

volumes:
    mysql-data:
        driver: local
